name: "Integration Tests"

on:
  workflow_dispatch: {}

  pull_request:
    types: [opened, synchronize, reopened]

env:
  AWS_REGION: us-east-2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Plan Atmos Component
        uses: ./
        with:
          component: "foobar"
          stack: "plat-ue2-sandbox"
          component-path: "components/terraform/foobar"
          terraform-plan-role: ${{ secrets.TERRAFORM_PLAN_ROLE }}
          terraform-state-role: ${{ secrets.TERRAFORM_STATE_ROLE }}
          terraform-state-bucket: ${{ secrets.TERRAFORM_STATE_BUCKET }}
          terraform-state-table: ${{ secrets.TERRAFORM_STATE_TABLE }}
          aws-region: ${{ env.AWS_REGION }}
